### ISSUE TITLE
Preps site sometimes lists wrong home/away teams when pulling from brackets

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#22]
Here's an example of the brackets:
http://www.denverpost.com/preps/ci_29020092/colorado-high-school-boys-soccer-2015-state-brackets

When it pulls into this page, it should list the higher-ranked team as home, but very frequently (not always) doesn't: http://preps.denverpost.com/sport/boys-soccer/

This is happening only when schedules are displayed on Max Preps in bracket format.

**Comment by freejoe76** [comment]
@danielboniface @morgandzakowic so it's wrong on the preps.denverpost page, but it's right on the www.denverpost page?

**Comment by danielboniface** [comment]
@freejoe76 @morgandzakowic  Yes... it's right in the www.denverpost embedded brackets. Wrong (sometimes, but not always) on the preps.denverpost page.

**Comment by freejoe76** [comment]
@danielboniface @morgandzakowic Can you tell me one or two of the matches on http://preps.denverpost.com/sport/boys-soccer/ that have the wrong home / away pairings?

**Comment by danielboniface** [comment]
3:30 p.m. Arapahoe at Rock Canyon Preview (should be at higher-seeded Arapahoe)
4:00 p.m. Monarch at Mountain Vista Preview (should be at higher-seeded Monarch)
4:00 p.m. Heritage at Bear Creek Preview (should be at higher-seeded Heritage)

I already fixed Broomfield on manually...it was also backwards. @freejoe76 @morgandzakowic

**Comment by freejoe76** [comment]
@danielboniface When you fixed it, how did you fix it?

**Comment by danielboniface** [comment]
@freejoe76 Manual fixes are done through team player: http://denver.newsengin.com/teamplayer/index.php

**Comment by freejoe76** [comment]
This is an ingestion issue, which is code I don't have control over. @danielboniface can you take this up with NewsEngin?

**Comment by danielboniface** [comment]
This is an issue with MaxPreps. Their information is coming over incorrect in the feed. I talked with Gerry Valerio over there and they have their dev team working to fix the problem. cc @freejoe76

**Comment by freejoe76** [comment]
Thanks Dan!
