### ISSUE TITLE
Get the preps site publishing the winter sports

### ISSUE THREAD

**Issue by freejoe76** [denverpost/preps#23]
http://preps.denverpost.com/sport/boys-basketball/ doesn't have anything on it, and it should.

**Comment by danielboniface** [comment]
Winter (sports) is coming.

**Comment by freejoe76** [comment]
Okay, one of the problems: Boys basketball still had 10 games active from 2014. This is fixed, also, this is a production issue. I found the games by searching in Newsengin's TeamPlayer for all boys basketball games from Nov. 2014 to June 2015. cc @morgandzakowic

**Comment by freejoe76** [comment]
I see two games scheduled for week two of the boys basketball season: http://preps.denverpost.com/home.html?site=default&tpl=Schedule&Sport=6&SearchDate=12/13/2015&SearchDateEnd=12/19/2015&start=0&count=500&Week=2 ... I'm guessing there should be more than that.

**Comment by freejoe76** [comment]
I don't see any ice hockey games in December in the NewsEngin admin, should there be games in there? @morgandzakowic @danielboniface 
<img width="504" alt="screen shot 2015-12-01 at 11 03 55 am" src="https://cloud.githubusercontent.com/assets/125554/11509434/4d9e27b6-981b-11e5-853d-5af7ad7c0d97.png">

**Comment by danielboniface** [comment]
Looking on the Chsaanow.com site, looks like there are hockey games this week: http://chsaa.sportngin.com/schedule/day/league_instance/37098/2015/12/1?subseason=264914&referrer=2209117

**Comment by freejoe76** [comment]
Looks like NewsEngin fixed it! For future reference, @danielboniface @morgandzakowic, NewsEngin's help desk site is here: https://newsengin.zendesk.com/

**Comment by freejoe76** [comment]
What you want the search interface to look like, for reference.
<img width="597" alt="screen shot 2015-12-02 at 10 54 24 am" src="https://cloud.githubusercontent.com/assets/125554/11539189/1e7df52e-98e3-11e5-8ca8-d73079a1ee29.png">
