### ISSUE TITLE
Team records are not appearing in boxscores

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#25]
Team records are not appearing in boxscores.
Here's an example:
http://preps.denverpost.com/boxscores/218654/
![overall-records](https://cloud.githubusercontent.com/assets/9724494/12245699/6b788c10-b867-11e5-83e5-55227a24caba.png)

**Comment by freejoe76** [comment]
This is fixed. There were some hard-coded "2014"'s in the query template in the NewsEngin admin. I added some code to make it clearer that's something we need to address on the basketball box score, though the other sports will probably need the same treatment.
