### ISSUE TITLE
Auto-tag schools, players in NGPS articles to respective pages on preps.denverpost.com

### ISSUE THREAD

**Issue by danielpetty** [denverpost/preps#4]
Requesting that names of players and schools be linked automatically to the appropriate player page and/or team page to begin establishing SEO benefit and benefit for the user.

So on first mention of Mike Morian's name in this article:

http://www.denverpost.com/preps/ci_27179856/mike-morean-cherry-creek-wins-2014-gold-helmet-award

Links to here: http://preps.denverpost.com/players/mike-morean/299998/

**Comment by freejoe76** [comment]
This is the first draft of the proper-noun matching js: https://gist.github.com/freejoe76/9cbfb00f043935efa4c0

**Comment by freejoe76** [comment]
Schools is done and launched (example: http://www.denverpost.com/preps/ci_28740061/2015-colorado-high-school-football-class-5a-capsules ) -- players involves loading 2MB of javascript on the page, as well as significant time spent combing through the article looking for potential player names to hyperlink. Doing players isn't worth the client-side costs. This is done.

cc @morgandzakowic
