### ISSUE TITLE
Update Preps scoreboard for fall

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#40]
Hello, please update the preps.denverpost.com scoreboard for fall sports. @freejoe76 left instructions in the "Read Me" section here on how to do that.

Thanks!

**Comment by danielboniface** [comment]
Hey @schneidan, I'm told that MaxPreps has turned on the fall sports feeds, and NewsEngin is seeing the content flowing into the following:
-- Football
-- Field hockey
-- Softball
-- Boys soccer
-- Girls volleyball

**Comment by schneidan** [comment]
okay. I'll try to do the season update again this afternoon, then. thanks!

**Comment by schneidan** [comment]
Going to call this done.
