### ISSUE TITLE
Add a Post Preps thumbnail as a default image on preps.denverpost.com

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#41]
Hello, would it be possible to add a generic Post Preps image to all pages on preps.denverpost.com so that we can share them on Facebook and Twitter and have some sort of default image get scraped?

For example, if I share the Week 1 volleyball schedule on our Post Preps Facebook page, no image is found: http://preps.denverpost.com/home.html?site=default&tpl=Schedule&Sport=11&SearchDate=08/20/2017&SearchDateEnd=08/26/2017&start=0&count=500&Week=1

**Comment by schneidan** [comment]
Do you have an example of the type of image you'd like?
