### ISSUE TITLE
Can you throw this on an extras page

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#43]
I'd like to iframe this into a story. Can you add it to an extras page and send me the link?
```
<div id='wowza_player'></div>
<script id='player_embed' src='//player.cloud.wowza.com/hosted/rffvwpv9/wowza.js' type='text/javascript'></script>
```

**Comment by schneidan** [comment]
Did you say Lubbers did one like this for you before? Where did it wind up?

**Comment by danielboniface** [comment]
Lubbers has something set up where he drops code/files in quickly to add to the newsletter. So it ended up in a newsletter folder on extras.

**Comment by schneidan** [comment]
okay dokey. Just did the same:

http://extras.denverpost.com/newsletter/post-preps-video-game-of-the-week.html

**Comment by danielboniface** [comment]
Thanks!
