### ISSUE TITLE
Can someone throw this onto an Extras page and send me the link?

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#44]
```
<div id='wowza_player'></div>
<script id='player_embed' src='//player.cloud.wowza.com/hosted/0ffsl9tz/wowza.js' type='text/javascript'></script>
```

Thanks!

**Comment by schneidan** [comment]
Done.

http://extras.denverpost.com/newsletter/post-preps-gow-20170907.html

**Comment by schneidan** [comment]
@danielboniface I went one better on this:

Now you can do these on your own with this URL:
`http://extras.denverpost.com/newsletter/post-preps-video-player.html?player= 0ffsl9tz `

Just notice that unique ID in the URLs you've been requesting -- it's like an 8-character alphanumeric string (`0ffsl9tz` in this case). Just use this same URL and change the `?player=` to that string and it will dynamically create that script tag.
