### ISSUE TITLE
Get preps.denverpost.com updated for winter sports

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#45]
Hello,

It's that wonderful time of year again when we would like to update preps.denverpost.com for winter sports. Please do all your magic to make those winter sports take prominence on the preps stats/schedules site.

I have submitted a ticket with NewsEngin to re-scrape all our winter sports, and make sure the feeds are all turned on.

Dan

**Comment by schneidan** [comment]
I don't see anything specific listed for winter sports in the README so I don't know what, if anything, needs to be done...do you?

**Comment by danielboniface** [comment]
I think it's same process we'd do for spring, if there is a note in there about it, except we want this sports to be the most prominent:

Boys Basketball
Girls Basketball
Ice Hockey
Girls Swimming and Diving
Wrestling
