### ISSUE TITLE
Can you create an extras page we can iframe as a right-rail widget?

### ISSUE THREAD

**Issue by danielboniface** [denverpost/preps#47]
It should have a headshot photo of Kyle Newman and the following text underneath:

**Post Preps Insider** is your daily source for news, story lines, top games and more information on Colorado high school sports -- brought to you by Denver Post preps editor Kyle Newman.

![kyle-newman-mug](https://user-images.githubusercontent.com/9724494/35012594-853bdd88-fac7-11e7-8077-2e7a3da0216c.jpg)

**Comment by schneidan** [comment]
Maybe the photo to one side next to the text? It will be rather huge if I let it be the full width of the column...

**Comment by schneidan** [comment]
Here you go: [dfm_iframe src="https://extras.denverpost.com/widgets/widget-preprail.html" width="100%" height="120px"]

**Comment by danielboniface** [comment]
Awesome, thanks Dan!

**Comment by danielboniface** [comment]
@schneidan If you get a minute would you link the text "Post Preps Insider" to this URL: https://www.denverpost.com/tag/post-preps-insider/

And the image of Kyle Newman to this URL: https://www.denverpost.com/author/kyle-newman/
