### ISSUE TITLE
Girls and boys lacrosse schedules still say playoffs

### ISSUE THREAD

**Issue by thejoenguyen** [denverpost/preps#5]
The boys and girls lacrosse schedules still have the words "state playoffs" on them.
http://preps.denverpost.com/sport/boys-lacrosse/
http://preps.denverpost.com/sport/girls-lacrosse/

**Comment by freejoe76** [comment]
Haha, looks like this was never set up for lacrosse.

**Comment by freejoe76** [comment]
Joe, I need the dates that the regular season ends for boys and girls lacrosse.

**Comment by danielpetty** [comment]
Starts on March 5. Regular season ends May 2. Finals are May 20. More info: http://chsaanow.com/2013-07-15/2014-2015-chsaa-sports-calendar/

**Comment by freejoe76** [comment]
This is fixed.
