### ISSUE TITLE
Some links on preps.denverpost.com still going to old URLs for schools/teams

### ISSUE THREAD

**Issue by danielpetty** [denverpost/preps#8]
I believe this is only happening on certain parts of the template:

http://preps.denverpost.com/sport/girls-soccer/

For instance, Denver Christian at the bottom is this URL:

http://preps.denverpost.com/home.html?site=default&tpl=Team&Sport=15&TeamID=10170

Note the school list all the way at the bottom of that page. cc: @morgandzakowic

**Comment by freejoe76** [comment]
Thanks Petty, I'll take a look at it.

**Comment by danielpetty** [comment]
Adding that Google appears to be indexing both pages for teams, resulting in lower results for both. See this search:

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Pine+Creek+High+School+Girls+Soccer

**Comment by danielpetty** [comment]
Also, this may be a separate issue, but suggesting for SEO friendliness to rename structure for teams to:

[name of school without phrase "High School"] [gender of sport] [sport]

i.e., Regis Jesuit Girls Soccer — Denver Post High School Sports

Possibly better: Regis Jesuit Soccer — Girls — Denver Post High School Sports

**Comment by freejoe76** [comment]
That's definitely a separate issue.

**Comment by freejoe76** [comment]
Re: multiple pages, that also is a separate issue.
